server :
   port : 8085

spring:     
    datasource : 
        password : 1995
        url: jdbc:mysql://localhost:3307/studentmanagement
        username : root
    boot :
      admin:
        client:
           url: http://localhost:9000 
    application :
       name: WlCOME-API-1          
     
      
management:
   endpoints:
       web:
        exposure:
          include : '*'
 
